### ISSUE TITLE
bam2fastq tool

### ISSUE THREAD

**Issue by lomereiter** [biod/sambamba#121]
- should group mates in a similar fashion as `markdup` does if the file is coordinate-sorted
- optionally output reverse-complemented reads if they are mapped to the negative strand
- single-file output, with '/1' and '/2' suffixes

**Comment by sjackman** [comment]
:+1: Yes, please!

**Comment by sjackman** [comment]
Optionally a dual-file output would be very useful. Many tools do not read interleaved paired-end FASTQ files.
See https://github.com/pachterlab/kallisto/issues/47

**Comment by sjackman** [comment]
Or better, implement the `-f` option to filter reads by their flags to separate forward and reverse reads.
See https://github.com/samtools/samtools/issues/402

**Comment by crazyhottommy** [comment]
Yes. please 2!

**Comment by jrherr** [comment]
Please! I 3rd this request!

**Comment by pjotrp** [comment]
Anyone want to help on adding this functionality? We can support it.

**Comment by sjackman** [comment]
To clarify, was this feature implemented?

**Comment by pjotrp** [comment]
No, sorry. Please sign up on the mailing list to discuss future directions.

https://github.com/biod/sambamba#getting-help
