### ISSUE TITLE
Indexing: pseudo-bin deviates from the spec

### ISSUE THREAD

**Issue by carsonhh** [biod/sambamba#210]
Sambamba index is incorrectly setting the offsets for the pseudo-bin on the very last reference sequence. Specifically, the unmapped_end value. According to the BAI specification unmapped_end is the file offset of the end of “placed” unmapped reads. However, Sambamba is setting this to the end of “un-placed” unmapped reads (i.e. contig ID '*'). This has adverse affects for downstream programs. Fully unmapped reads end up being included with reads belonging to the last real contig. Also programs that use the last pseudo-bin (when present) to help locate fully unmapped reads end up thinking there are no fully unmapped reads in the BAM file (for example samtools).

**Comment by lomereiter** [comment]
Thanks for reporting, at the time (2012) I had to reverse-engineer that bloody pseudo-bin described in the spec only two years later (https://github.com/samtools/hts-specs/commit/17a0201f8ca8eed140888e35c020a605fe07902f)

**Comment by jfarek** [comment]
Hi,

I've been encountering this issue recently and found that the issue originates from BioD. Applying this fix to the code sets the offset correctly ([file](https://github.com/biod/BioD/blob/b7f1db860d212ee5fb6f9adfb36c6e783aaeb6f5/bio/bam/bai/indexing.d)):

```
diff --git a/bio/bam/bai/indexing.d b/bio/bam/bai/indexing.d
index fec5662..a02a768 100644
--- a/bio/bam/bai/indexing.d
+++ b/bio/bam/bai/indexing.d
@@ -117,15 +117,17 @@ struct IndexBuilder {
         void updateMetadata(ref BamReadBlock read) {
             if (read.ref_id == -1) {
                 ++_no_coord;
-            } else if (read.is_unmapped) {
-                ++_unmapped;
             } else {
-                ++_mapped;
-            }
+                if (read.is_unmapped) {
+                    ++_unmapped;
+                } else {
+                    ++_mapped;
+                }

-            if (_beg_vo == -1UL)
-                _beg_vo = cast(ulong)read.start_virtual_offset;
-            _end_vo = cast(ulong)read.end_virtual_offset;
+                if (_beg_vo == -1UL)
+                    _beg_vo = cast(ulong)read.start_virtual_offset;
+                _end_vo = cast(ulong)read.end_virtual_offset;
+            }
         }

         void updateLinearIndex() {
```
