### ISSUE TITLE
too many open files during markdup

### ISSUE THREAD

**Issue by RichardCorbett** [biod/sambamba#229]
Hi there,

I am trying out one of your new versions that uses external sort to see how it works. On my first try I got the following error.  Do you have any suggestions?

thanks,
Richard

```
sambamba_v0.6.3 markdup -p --tmpdir . ./*bam merge.dup.bam
finding positions of the duplicate reads in the file...
[==============================================================================][                                                                              ]
sambamba-markdup: Cannot open file `./sambamba-pid82605-markdup-mryv/PairedEndsInfobtgg86' in mode `w+' (Too many open files)
```

**Comment by lomereiter** [comment]
Hi,

1) Working with lots of files at the same time often requires increasing the system limit on the number of open files. You can change it via `ulimit -n <larger number>`.
2) Increasing `--hash-table-size` and `--overflow-list-size` leads to larger memory consumption but fewer temporary files, so often also helps.
