### ISSUE TITLE
markdup options clarification

### ISSUE THREAD

**Issue by igordot** [biod/sambamba#240]
I really appreciate that markdup documentation specifically mention memory consumption based on the number of reads (although external sort is now implemented, so maybe that part is no longer relevant). Some of the parameters (`--hash-table-size` and `--overflow-list-size` and `--io-buffer-size`) seem to be related to memory. I saw some previous discussions where it was suggested to modify those parameters, but it's still not very clear to me how much of an effect they have. Is it possible to get more info on how they can be adjusted and/or what a reasonable range is?

**Comment by lomereiter** [comment]
Hi,

here's some more info, feel free to come up with documentation PRs ;)

`--io-buffer-size` should be ok by default, it might be even too large; its role is simply to reduce the number of disk seeks; whenever possible, it's best to use SSD for temporary files.

As for `--hash-table-size` and `--overflow-list-size`, the more the better, I'd suggest to set them to be around the same but that might be suboptimal. 
For the upper bound, take available RAM and divide by the typical read size (uncompressed). The latter can be estimated by running `sambamba view -f bam -l0` once piped into `wc -c` and once with `-c` and then dividing the two numbers. (It's feasible to optimize memory consumption here by stripping unnecessary information but it's not currently done.)
For the lower bound, there's a note in the documentation about `(average coverage) * (insert size)` which is roughly the number of unrelated records between a read pair when the file is coordinate-sorted. It's best if these unrelated records don't kick old reads out too early, in this scenario read pairs can be found even without the use of the overflow list. The overflow list is supposed to handle read pairs that are relatively far from each other (in other terms, right tail of the insert size distribution). If it's overfilled, temporary files are created, which brings extra overhead and might even lead to hitting the operating system limit on the number of simultaneously opened files.

**Comment by igordot** [comment]
For the upper bound, let's say you have 16 GB of RAM and 2x100 library (fairly reasonable numbers). 16,000,000,000/200 is 80,000,000. That is much higher than the default of 262,144. Is my calculation correct or is the default value very conservative?

Also, is the specified hash table size assigned to each thread or divided across all threads? In other words, does changing from 1 to 2 threads and keeping all other settings the same double the memory usage?

**Comment by lomereiter** [comment]
* The default value is indeed quite conservative, but your calculation is also a bit flawed: a single 100bp record occupies more than 100 bytes in memory because of read name, quality information, read group, and so on, up to 1KB if aligner decides to write lots of extra tags. Most of it could be stripped off for `markdup` purposes but it's not done since there's been no real need so far. Also there's not only Illumina on the market, those with ~500bp IonTorrent reads have different idea of 'reasonable'.
* Data structures are shared across threads, so the number of threads has no influence

**Comment by igordot** [comment]
I didn't realize you meant read length in bytes, not bases. Bytes makes more sense here.

One final question. I just realized that the hash table size sounds similar to Picard's MAX_RECORDS_IN_RAM option. Is using the same number for both going to result in similar memory usage or are they completely different?

**Comment by lomereiter** [comment]
No idea, but I'd guess memory usage in Picard would be higher by a constant factor because it generates lots of Java objects per each record. I skimmed through their `SortingCollection` and it doesn't seem to use any hash tables, MAX_RECORDS_IN_RAM is just the sorting buffer size.

**Comment by igordot** [comment]
Thanks for clarifying!
