### ISSUE TITLE
markdup: is it possible to collect statistics similar to Picard's DuplicationMetrics?

### ISSUE THREAD

**Issue by allwu** [biod/sambamba#241]
In `sambamba-markdup` is it possible to collect the duplication reports similar to the Picard DuplicationMetrics (https://broadinstitute.github.io/picard/picard-metric-definitions.html#DuplicationMetrics) emitted by specifying the _METRICS_FILE_? If not, is it possible to collect similar information from some log of the markdup run?

**Comment by lomereiter** [comment]
Not at the moment. Also, is there any interest in `READ_PAIR_OPTICAL_DUPLICATES`?

**Comment by isthisthat** [comment]
Yes please! This has become a very important metric with Illumina's HiSeqX.

**Comment by pjotrp** [comment]
Feel free to pick this up.
