### ISSUE TITLE
Sambamba slice doesn't handle multiple regions

### ISSUE THREAD

**Issue by eddiebroad** [biod/sambamba#258]
See the following commands:  

       samtools view -o samtools.bam -b  C835.HCC1143_BL.4.bam        1:2000000-2001000  2:2000000-2005000  
       sambamba_v0.6.5 slice -o sambamba.bam   C835.HCC1143_BL.4.bam  1:2000000-2001000  2:2000000-2005000  

 Even though the usage looks the same, and no errors are thrown, they output two different BAMs. Consistent with the "slice" usage notes (seen by entering just "sambamba_v0.6.5 slice") sambamba  generates outputs reads *only* from the first region (ignoring the second region) :  

       samtools view sambamba.bam |cut -f3|sort |uniq -c  
       2 1

 While samtools collects both regions:  

       samtools view samtools.bam |cut -f3|sort|uniq -c  
       2 1  
       4 2

Can the "slice" command be improved to handle multiple regions like samtools view [region [region...]]?

**Comment by pjotrp** [comment]
Hi @eddiebroad  - anyone in Boston willing to help add this?

**Comment by pjotrp** [comment]
@eddiebroad would you mind signing up to the mailing list so we can discuss the future? https://groups.google.com/forum/#!forum/sambamba-discussion
