### ISSUE TITLE
Add performance/regression test framework

### ISSUE THREAD

**Issue by pjotrp** [biod/sambamba#277]

**Comment by lomereiter** [comment]
OMG, I realized only now how horribly slow our binary releases are. No amount of compatibility with old systems can justify 1.5-2x difference in sorting time that I observe.

**Comment by pjotrp** [comment]
Hi Artem. I know we can be a lot faster. Question is where the regressions came from (probably something stupid).

The new ldc will help because it has a profiler and LLVM can optimize based on the profiler (easily leading to 15% gain). Using a newer LLVM and htslib will help too. But I will start with that after we have the framework. I don't feel confident switching without proper testing at scale. With that in place we can even switch to older versions of sambamba and bisect results.

I will add the performance tests, but probably not before April. I am silly busy this month. Support for sambamba is high on my list because I know how many people are using it.

**Comment by lomereiter** [comment]
The regressions don't even come from the code, it's all about build toolchain.
Easily could be wrong flags used somewhere.

**Comment by pjotrp** [comment]
In Makefile.guix I use different flags. You can test that release at 

     [1]http://biogems.info/contrib/genenetwork/s5ipll9mbd4kw2mxy6v4zalhh9wvvzf2-sambamba-0.6.6-52ab1ef-x86_64.tar.bz2
     md5sum a238c26b30eb57d992d7a5c11c0ab8ee

note that we can get a lot more aggressive at optimizations.

**Comment by pjotrp** [comment]
Getting close to a new release.

**Comment by pjotrp** [comment]
Fixed.
