### ISSUE TITLE
Update benchmark results

### ISSUE THREAD

**Issue by lomereiter** [biod/sambamba#283]
Develop branch of Samtools finally has a multithreaded decoder used by the tools: https://github.com/samtools/samtools/commit/24971add7fb21e201b5c415b01b69ce9b46042e4

**Comment by lomereiter** [comment]
@pjotrp we need new benchmarks vs samtools. Version 1.4 was released recently with multithreaded reading (finally!), so simple reading/writing (=decompression/compression) is apparently head-to-head, interesting to see more complicated stuff like sort/merge/whatever else is comparable.

**Comment by pjotrp** [comment]
https://github.com/biod/sambamba/blob/master/test/benchmark/stats.org
