### ISSUE TITLE
filtering by strand pair orientation

### ISSUE THREAD

**Issue by avilella** [biod/sambamba#286]
Hi,

I have read the filtering syntax of sambamba view here:
https://github.com/lomereiter/sambamba/wiki/%5Bsambamba-view%5D-Filter-expression-syntax

And I am wondering what's the right command to filter the reads of the following orientations, using the arrow terminology in the link below:

https://ppotato.files.wordpress.com/2010/08/slide1.png

1) Exclude singletons, non-paired, unaligned, exclude not primary (256), exclude not passing vendor qc (512) and then:

2) keep only reads with the following orientations:
```
-->--> and <--<--
```
which according to my interpretation of the flags in the link above should be flags: 65+67+129+131 and 113+177+115+179

Currently, I can get as far as filtering for (1), but not for (2):

```
sambamba view -F "not (unmapped or mate_is_unmapped) and not failed_quality_control and not secondary_alignment" $i -f bam -o foo.bam
```

Any ideas how to so such filtering?

**Comment by avilella** [comment]
I found a way that seems unnecessarily complicated:

```
sambamba view -F "not (unmapped or mate_is_unmapped) and not (failed_quality_control) and (not secondary_alignment) and (not ((not mate_is_reverse_strand and reverse_strand) or (not reverse_strand and mate_is_reverse_strand)))"
```

Can it be simplified?

**Comment by lomereiter** [comment]
Hi,

Unfortunately it can't be simplified at the moment. You are asking essentially the same as https://github.com/lomereiter/sambamba/issues/216 but for slightly different use case.
For the flags I could in principle quickly add `xor` operator. Another idea would be to add `orientation` filter, e.g. `orientation == '>>' or orientation == '<<'`.

**Comment by pjotrp** [comment]
May reopen later.

**Comment by paulstretenowich** [comment]
Hi,
I'm trying to filter the reads oriented as FR only but I don't think it's feasible with sambamba. Any thoughts if it's already doable or planned to be included?
Thanks,
Paul
