### ISSUE TITLE
sambamba mpileup has problems.

### ISSUE THREAD

**Issue by FWTT** [biod/sambamba#288]
- There are differences in the results depending on whether you give the -l option in --samtools or the -L option in sambamba.
- There are duplicate values with less computation in one loci .

----
I attach the [relevant data](https://docs.google.com/presentation/d/1tVxvJzW8x7lFG7pTws9Bc9e-iKN-LwqwSiou0PFatS0/pub?start=false&loop=false&delayms=3000&slide=id.g206388bf0b_0_0)

**Comment by pjotrp** [comment]
Nice picture :). Clearly sambamba interprets the bed file differently by being 1 offset rather than 0.
@lomereiter any comment?

**Comment by lomereiter** [comment]
The screenshots are helpful but I'd like a little more information, in this case the full command line at least.

I've created the [issue template](https://raw.githubusercontent.com/lomereiter/sambamba/master/.github/issue_template.md) that will be shown for new bug reports, @pjotrp please have a look and edit if you wish.

**Comment by pjotrp** [comment]
Template might help. But going from that output you can see it is 0 or 1 indexed. Probably easy to replicate. If not, it is not a problem.
