### ISSUE TITLE
Sambamba view fails if command line supplied regions are not in sort order

### ISSUE THREAD

**Issue by carsonhh** [biod/sambamba#294]
sambamba version 0.6.6

sambamba view fails whenever you supply multiple regions that are not in sort order on the command line. Perhaps sambamba should be sorting the regions the user gives internally as the first step before processing?

This works --> sambamba view -f bam -o test.bam 0.bam 1 2

This fails --> sambamba view -f bam -o test.bam 0.bam 2 1

sambamba-view: BAM file is not coordinate-sorted: read 'ST-E00267:147793196:H277TCCXX:2:1107:30252:46859' (0:10365) must be after read 'ST-E00267:147793196:H277TCCXX:2:1214:22538:28576' (1:243152585)' (at virtual offsets 2705500/43849, 2705500/44306)

**Comment by lomereiter** [comment]
Nice catch!

I guess it makes more sense to unset 'coordinate' order in the header and not create an index.

**Comment by carsonhh** [comment]
Why not just sort the user defined regions before producing the file? I really can't think of a case where a user would want a return file that is out of order. But I can see how supplying regions in sort order may be difficult for the user, especially for non-human genomes where you may have several thousand named contigs like PMAR_23545CDF that don't have obvious sort orders like chromosomes do (i.e. 1, 2, 3, 4). So having 'view' put them in order before generating the file would seem like the more useful behavior.

**Comment by pjotrp** [comment]
Closing. May reopen at some point.
