### ISSUE TITLE
sambamba depth base result discrepancies

### ISSUE THREAD

**Issue by harperfauni** [biod/sambamba#295]
Hi,

My name is Harper and I am currently using sambamba 0.6.6 in order to see the coverage for each base in a specific region. I was particularly looking at the gene LOC729737 and the UCSC genomic coordinates for it is 1:134772-140566 (0-based) using a bed file. 

The bed file looks like:

1    134772    140556

My command is:

sambamba depth base -z -L bed file bam file | head -n15

The results are:
Processing reference #1 (1)
REF     POS     COV     A       C       G       T       DEL     REFSKIP SAMPLE
1       134772  8       0       0       0       8       0       0       sample
1       134773  8       0       8       0       0       0       0       sample
1       134774  8       0       0       8       0       0       0       sample
1       134775  8       0       0       0       8       0       0       sample
1       134776  8       0       0       8       0       0       0       sample
1       134777  8       0       0       8       0       0       0       sample
1       134778  8       0       0       8       0       0       0       sample
1       134779  8       0       8       0       0       0       0       sample
1       134780  8       0       0       8       0       0       0       sample
1       134781  8       8       0       0       0       0       0       sample
1       134782  8       0       0       0       8       0       0       sample
1       134783  9       9       0       0       0       0       0       sample
1       134784  10      0       0       0       10      0       0       sample
1       134785  10      0       0       0       10      0       0       sample

Looking at IGV (coordinates/positions translated into 1-based) with the 14 positions above, I saw a read depth of 11 or higher. I was wondering if sambamba was looking at a different region and generated an incorrect coverage value. What would be some explanations as to why I am seeing discrepancies in coverage values when looking at sambamba results and in igv when 0-based/1-based conversion has been taken into consideration? I was also wondering if indel regions could possibly affect sambamba depth base output. 

Thanks and have a nice day!

**Comment by lomereiter** [comment]
Hi,

Reads with duplicate/failed QC flag or mapping quality=0 are excluded by default. You can tweak this using `-F` flag.

**Comment by nathanhaigh** [comment]
Hi @harperfauni, IGV will by default display:
- MAPQ 0 alignments
- Secondary and Supplementary alignments
- Vendor QC failed reads
- Duplicate reads

Take a look at IGV's settings, and you might be able to remove from display, the reads which `Sambamba` is also removing: https://software.broadinstitute.org/software/igv/Preferences#Alignments

 0 reads
