### ISSUE TITLE
sambamba merge messed up a read's chromosome

### ISSUE THREAD

**Issue by zeus19900814** [biod/sambamba#303]
I have two small bam files here.

https://www.dropbox.com/s/bw6hy7hilvto4n9/A.bam?dl=0
https://www.dropbox.com/s/746adkjrhg4jpkt/B.bam?dl=0

I ran sambamba merge (both single and multi threaded) on them.
For read J00126:103:HCJ7NBBXX:7:1202:14357:46768, its chromosome is chr2 in A.bam but is chr12 in the output merged bam. I am not sure why sambamba behaved like this but I suspect it might have something to do with chromosome orders(or chromosome order index) in bam header. 

Thank you for any help!

Zheng

**Comment by lomereiter** [comment]
Background: BAM files have both a binary section containing list of chromosome names and lengths, and the SAM header that also has the list of chromosomes (SQ lines). As of now, sambamba relies on the assumption that these lists are in the same order, but apparently that's not always the case, and it seems that the format specification allows this. 
A short-term fix on your side would be to replace SAM headers to put them in sync with the binary section (which seems to be sorted lexicographically, see e.g. `sambamba view -I A.bam`):
```bash
#!/usr/bin/env bash
# Usage: <script> <bam file>

INPUT=$1
samtools view -H $INPUT | grep -v @SQ > $INPUT.hdr
samtools view -H $INPUT | grep @SQ | LC_ALL=C sort -k 2 > $INPUT.seq
cat <(head -n1 $INPUT.hdr) $INPUT.seq <(tail -n +2 $INPUT.hdr) > $INPUT.new.header
samtools reheader -P $INPUT.new.header $INPUT > $INPUT.reh.bam
mv $INPUT.reh.bam $INPUT
rm $INPUT.hdr $INPUT.seq $INPUT.new.header
```

**Comment by zeus19900814** [comment]
Thanks! I will modify the bam files!
