### ISSUE TITLE
Sambamba slice using bed file regions

### ISSUE THREAD

**Issue by godotgildor** [biod/sambamba#306]
I was thinking about adding the ability to provide a bed file as input to the sambamba slice command.  Looking at the view code, I see that there you just call parseBed which returns an array of BamRegions.  The slice code block on the other hand expects an array of Regions.  Looking at the difference between these two structs, it appears that Region simply has the chr name, start coord, and end coord.  The BamRegion has the index of the chr in the bam header, the chr start, and chr end.  

My naive approach is to update the BamRegion struct to also have an optional field for the chr name.  In the parseBed function it would then store the index to the chr in the bam header, the start and stop coords, and then also the chr name.  Then after parsing the bed, one could iterate over the array of BamRegions and easily convert to an array of Regions, and this could be passed to the slice logic.  Does that sound reasonable?  

I suppose an alternative way would be to keep BamRegion and parseBed the same, and then create a helper function that takes an array of BamRegions and a Bam file, iterates over the BamRegion, gets the chr index, uses that to look up the chr name in the bam header, and create an array of Regions with that info.  

Do you have thoughts on which approach would be cleaner/preferable or perhaps other ideas?

**Comment by lomereiter** [comment]
Hi, your first approach sounds reasonable.
You can easily turn reference ID into a name via `bam.reference(id).name`, and the whole process can be accomplished as 
```d
regions = bam_regions.map!(r => Region(bam.reference(r.ref_id).name, r.start.r.end))
```

**Comment by godotgildor** [comment]
That's very helpful.  Thanks.  I'll look at making these changes in the next week or so.

**Comment by pjotrp** [comment]
Any progress on this one?
