### ISSUE TITLE
[Feature Request] Extract or exclude alignments with QNAMES found in input file. 

### ISSUE THREAD

**Issue by changcw83** [biod/sambamba#313]
I have modified sambamba to be able to do it but this is the first time I'm contributing so would need some guidance.

**Comment by lomereiter** [comment]
Hi, I see that you forked the repo, so now you should: (assuming zero familiarity with git)
- run `git clone --recursive <your fork URL>` and `cd` into the cloned directory
- create and switch to that new branch: `git checkout -b qname`
- run `git commit` and enter a short but descriptive commit message
- run `git push` to push these changes to Github
- create a pull request using Github user interface, selecting the new branch
- then I'll be able to review the changes and provide suggestions, and eventually merge the branch

**Comment by pjotrp** [comment]
Please send us a github pull request. https://help.github.com/articles/about-pull-requests/
