### ISSUE TITLE
mpileup hangs if samtools would give empty output

### ISSUE THREAD

**Issue by vladmihaisima** [biod/sambamba#315]
In case mpileup command is run with a BED file to restrict the regions, sambamba will hang if there is no output from samtools (ie: there is nothing in those specific regions).

Attached you can find some simple files to reproduce the error. The script assumes that samtools 1.3 
[bug_sambamba_pileup.tar.gz](https://github.com/lomereiter/sambamba/files/1317106/bug_sambamba_pileup.tar.gz)
and sambamba_v0.6.6 are in PATH.

The command "sambamba_v0.6.6 mpileup -L toy.bed toy.sorted.bam -o pileup_with_bed.txt" will hang.

I have found this while doing unit tests for a more complex case, but I guess issue could show on a real case as well and it might be quite confusing.

**Comment by pjotrp** [comment]
Can you try and write a fix?

**Comment by pjotrp** [comment]
Delegated to later. Note use of sambamba mpileup is no longer recommended.

**Comment by VinoVino** [comment]
Why is the use of sambamba mpileup no longer recommended?  
The speedup relative to samtools mpileup was enticing.
