### ISSUE TITLE
Filtering using floats

### ISSUE THREAD

**Issue by karel-brinda** [biod/sambamba#318]
I would be great if it was possible to filter the alignments using floats. I have a float tag `hf` and want to keep only those records having `hf>0.5`.

This works:
```
sambamba view -F '[hf]>0'
```

This doesn't:
```
sambamba view -F '[hf]>0.5'
```

Error: `sambamba-view: invalid symbol in input stream at position 6`

**Comment by pjotrp** [comment]
Feel free to submit a pull request. It is not too hard.

**Comment by pjotrp** [comment]
Delegated to later.
