### ISSUE TITLE
Failed to build due to undefined reference

### ISSUE THREAD

**Issue by changhw01** [biod/sambamba#320]
Hello,

I followed the instruction in the README to install and build the current sambamba version (v.0.6.6 I believe) on a Ubuntu14.04 VM, but got the following error message:

gcc -Wl,--gc-sections -o build/sambamba build/sambamba.o -Lhtslib -Llz4/lib -Wl,-Bstatic -lhts -llz4 -Wl,-Bdynamic -l:libphobos2-ldc.a -l:libdruntime-ldc.a  -lrt -lpthread -lm -ldl
build/sambamba.o: In function `_D6undead6stream6Stream16doFormatCallbackMFwZv':
/home/hwchang/sambamba/undeaD/src/undead/stream.d:1217: undefined reference to `_D6undead3utf6toUTF8FNaNbNiNfNkJG4awZAa'
collect2: error: ld returned 1 exit status
make: *** [sambamba-ldmd2-64] Error 1

Those names look like random hashed names. Do you have any clue about what I might do wrong?

**Comment by pjotrp** [comment]
Should work with latest tree.

**Comment by rekado** [comment]
Unfortunately, I get the same error when building version 0.6.7 with Guix.

I'm using ldc 1.7.0.

**Comment by rekado** [comment]
It is fine with version 0.6.7-10-g223fa20 (i.e. current version from git), after minor changes to the linkage options.  Version 0.6.7 does not seem to build as is.

**Comment by pjotrp** [comment]
The package I use is in https://gitlab.com/genenetwork/guix-bioinformatics/blob/master/gn/packages/sambamba.scm

**Comment by rekado** [comment]
Ours is here:
http://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/bioinformatics.scm#n10999

**Comment by pjotrp** [comment]
Hi @rekado. Both definitions are comparable. I have a test/check target and I enforce samtools to be a dependency (sambamba calls samtools and bcftools for parallel pileup, though arguably that functionality is considered obsolete). Also I don't rebuild lz4. Those are the differences. In the future I hope to use standard htslib and turn BioD in to a shared library. But I am too busy for now... I'll toy with the new LLVM6 package in Guix soon - if that works it is time for a new sambamba release.

**Comment by pjotrp** [comment]
Ah yes, mine also does a parallel build.

**Comment by rekado** [comment]
We also don't rebuild lz4; we simply link with the existing lz4 (dynamically).

What is the purpose of the Makefile.guix?  I still needed to patch it, so I ended up not using it at all.  For your recipe you could use `#:make-flags '("-f" "Makefile.guix")` instead of having to replace the `'build` phase completely.

**Comment by pjotrp** [comment]
Makefile.guix is what I use. It is aimed at Guix and less generic. And yes, sure, make-flags is a nice improvement.
