### ISSUE TITLE
Sambamba hangs on a bam file without reads

### ISSUE THREAD

**Issue by choesang** [biod/sambamba#321]
Sambamba version 0.6.5 hangs on a bam file which just contains the
header but no reads. 

Samtools version:  1.2 with hts 1.2.1

Sambamba was invoked with following command line

sambamba mpileup -o /export/mpileup/Run1_bsa-B1hUgpJA-_1-ready.mpileup
-t 3 -b 200000000
/export/Run1_bsa-B1hUgpJA-_1/Run1_bsa-B1hUgpJA-_1-ready.bam --samtools
-A -B -Q 0 -d 1000000000 -f /opt/hg19/seq/hg19.fa

This bam was the consequence of a water sample being included in an
analysis run with 64 samples.
The test was run on Ubuntu 14.04 LTS within a docker container. The
error also occurs on the latest release version v0.6.6.

GDB backtrace of the hanging process:

(gdb) bt
#0  0x000000000049e338 in
bio.bam.pileup.PileupChunkRange!(bio.bam.splitter.ReadRangeSplitter!(std.range.interfaces.InputRange!(bio.bam.read.BamRead).InputRange,
"a.size_in_bytes").ReadRangeSplitter).PileupChunkRange.this(bio.bam.splitter.ReadRangeSplitter!(std.range.interfaces.InputRange!(bio.bam.read.BamRead).InputRange,
"a.size_in_bytes").ReadRangeSplitter, bool, ulong, ulong) ()
#1  0x000000000040af19 in
sambamba.pileup.pileup_main(immutable(char)[][]) ()
#2  0x000000000058fe8f in rt.dmain2._d_run_main(int, char**, extern(C)
int(char[][]) function).runAll().__lambda1() ()
#3  0x000000000058fe54 in rt.dmain2._d_run_main(int, char**, extern(C)
int(char[][]) function).tryExec(scope void() delegate) ()
#4  0x000000000058fd84 in _d_run_main ()
#5  0x00007f5f9140cf45 in __libc_start_main () from
target:/lib/x86_64-linux-gnu/libc.so.6
#6  0x0000000000404959 in _start ()

The bam without reads is attached.
[Run1_bsa-B1hUgpJA-_1-ready.bam.zip](https://github.com/lomereiter/sambamba/files/1430396/Run1_bsa-B1hUgpJA-_1-ready.bam.zip)

**Comment by pjotrp** [comment]
Thanks @choesang. Can you try fix sambamba?

**Comment by pjotrp** [comment]
delegated to later.
