### ISSUE TITLE
Sambamba view is dropping reads when you specify a region

### ISSUE THREAD

**Issue by carsonhh** [biod/sambamba#323]
sambamba 0.6.6

Sambamba view is dropping reads when you specify a region.

I have attached an example BAM that replicates the issue (it is gzipped to get GIT to allow me to attach it to the issue). The BAM contains only reads aligned to phix.

If you run sambamba view on the whole file, you get all reads back.
>$ sambamba view phix.bam | grep -c ""
68213

But if you specify the region as part of the view command, it loses reads that are aligned to phix.
>$ sambamba view phix.bam phix | grep -c ""
68208

These are the reads lost -->

> HIDSEQ-D00784:30:HK5MNBCXX:1:1112:18797:80069	133	phix	1	0	*	=	1	0	TTAAATTTAAACAAGAGCATTTCTACCATGAAGAAAATGTTACTTCTTTCTAAACCCGGTCTTTAACAACCTTCCAAGCATTTTTAGCCACTTTTCCTCC	####################################################################################################	AS:i:0	XS:i:0	RG:Z:1653321a_4MC:Z:1S99M	MQ:i:60
> 191d189
> HIDSEQ-D00784:30:HK5MNBCXX:2:1113:15799:94697	133	phix	1	0	*	=	1	0	CCATTTTTAAAAATGCTGCACTGGTTCCTTGGCAGGGCCTCAAATGTGAAAAGTGACTCAAGGGAGCAATGGGCGAGCCTGGACCTACTTGACCCTCCGT	0<00<F1<DH1C11<1111<11111111<111<1<//0001<@11<1<F1<1111111<<C11010<C################################	AS:i:0	XS:i:0	RG:Z:1653321a_4MC:Z:29S71M	MQ:i:60
> 259d256
> HIDSEQ-D00784:30:HK5MNBCXX:2:2103:18309:66343	1157	phix	1	0	*	=	1	0	AGTGTCAAGGAGGAAATCTCTACCGTGAGGAAGGTGTGAATCATATGTGAACCAGTGCTTGGCGAACGTGCAAGGCATGTGAAGCGCCGGCTCCTAGTCC	0000011<11<1001<1111111<<1<C011D####################################################################	AS:i:0	XS:i:0	RG:Z:1653321a_4MC:Z:18S82M	MQ:i:60
> 324d320
> HIDSEQ-D00784:30:HK5MNBCXX:2:2214:16545:4480	133	phix	1	0	*	=	1	0	GTAATTGCAACTCTAGTAAAATGACAACACAGGGATCTCTACAATGAACACATTGAGCCACATATCTAAACAGGCAATACTCGCACACGCCCAGTAAAAT	0000<1111<111<11<1<11<D1<@1DC111<0<D1<C111111<11<1111<11<1<11<<C1<1DE1F11D111<11110/<C##############	AS:i:0	XS:i:0	RG:Z:1653321a_4MC:Z:18S82M	MQ:i:60
> 742d737
> HIDSEQ-D00784:30:HK5MNBCXX:2:2116:7279:30398	181	phix	1	0	*	=	1	0	CCCGAAGCTGAGGCTCAGTCTGATTATGGACAGCTTCTGGGGAAGTAGCGCCAGCATAGTTTTTGGTGCGTTGTTTCATTCTTTCGATCCTAGACCTTTA	C</1<1111<11111D<11<1<<111<D1D<1<1<1011<F<11/</0<01<11<1<10111C1/<<</11111<1<1<</0<00111<1111110<0<0	AS:i:0	XS:i:0	RG:Z:1653321a_4MC:Z:22S78M	MQ:i:60

[phix.bam.gz](https://github.com/biod/sambamba/files/1463055/phix.bam.gz)

**Comment by pjotrp** [comment]
Maybe related to https://github.com/biod/sambamba/issues/311
