### ISSUE TITLE
Mark Duplicate for Scaffolds

### ISSUE THREAD

**Issue by wangshun1121** [biod/sambamba#326]
I am trying to call SNPs of [Phyllostachys heterocycla](http://202.127.18.221/bamboo), whose genome was assembled to Scaffold level. I mapped reads with bwa men and sorted and indexed bamfiles, then I tried to use sambamba to mark duplicate reads, and I received errors below:

```
1sambamba-markdup: More than 16383 reference sequences are unsupported
```

is there any suggestions for this?

sambamba v0.5.9

**Comment by pjotrp** [comment]
Please use the mailing list https://github.com/biod/sambamba#getting-help
