### ISSUE TITLE
undefined reference when trying to make sambamba

### ISSUE THREAD

**Issue by najoshi** [biod/sambamba#329]
I'm getting an error when making sambamba:

gcc -Wl,--gc-sections -o build/sambamba build/sambamba.o -Lhtslib -Llz4/lib -Wl,-Bstatic -lhts -llz4 -Wl,-Bdynamic -lphobos2-ldc -ldruntime-ldc  -lrt -lpthread -lm -ldl
build/sambamba.o: In function `_D6undead6stream6Stream16doFormatCallbackMFwZv':
/data/src/joshi/sambamba-0.6.7/undeaD/src/undead/stream.d:1217: undefined reference to `_D6undead3utf6toUTF8FNaNbNiNfNkJG4awZAa'
collect2: error: ld returned 1 exit status
make: *** [sambamba-ldmd2-64] Error 1

I found the same issue reported [here](https://github.com/biod/sambamba/issues/320), and the issue was closed saying that the latest tree worked, but it doesn't work for me. I cloned the latest repo and I installed the latest ldc. I tried many different things to get it to work, but to no avail. Any help would be highly appreciated.

**Comment by pjotrp** [comment]
See I have update the instructions. Please try again. See https://groups.google.com/forum/#!topic/sambamba-discussion/V_jQjdjL1gY
