### ISSUE TITLE
Markdup v0.6.6 Quits without error

### ISSUE THREAD

**Issue by ATpoint** [biod/sambamba#330]
sambamba markdup -r -t 7 -p -l 5 --tmpdir=./ --hash-table-size=1000000 --overflow-list-size=1000000 --sort-buffer-size=8000 --io-buffer-size=8000 in.bam out.bam
finding positions of the duplicate reads in the file...
[=============================]
  sorted 150414610 end pairs
     and 1969522 single ends (among them 0 unmatched pairs)
  collecting indices of duplicate reads...   done in 46008 ms
  found 284336375 duplicates
collected list of positions in 9 min 52 sec
removing duplicates...
[                                                                              ]sambamba-markdup: Invalid argument

Any idea what is happening?

**Comment by pjotrp** [comment]
Not sure. Can you give me something I can replicate?

**Comment by pjotrp** [comment]
https://github.com/biod/sambamba#getting-help
