### ISSUE TITLE
Error with make sambamba-ldmd2-64 command?

### ISSUE THREAD

**Issue by shreyashruti** [biod/sambamba#332]
$make sambamba-ldmd2-64

> which: no ldmd2 in (/root/ldc2--linux-x86_64/bin/:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/syslogin/.local/bin:/home/syslogin/bin:/home/syslogin/ldc/bin)
> ./gen_ldc_version_info.py  > utils/ldc_version_info_.d
> make: *** [ldc-version-info] Error 1
> 
I installed ldc latest version. still the error

**Comment by pjotrp** [comment]
I have update the instructions. Please try again. See https://groups.google.com/forum/#!topic/sambamba-discussion/V_jQjdjL1gY
