### ISSUE TITLE
Index documentation incorrect

### ISSUE THREAD

**Issue by stephenwilliams22** [biod/sambamba#336]
Hi,
Just wanted to let you know that your github documentation about number of threads for indexing is incorrect

SYNOPSIS
sambamba index [-p|--show-progress] [-n|--threads=NTHREADS] <input.bam> [<output.bai>]

should be

SYNOPSIS
sambamba index [-p|--show-progress] [-t|--nthreads=NTHREADS] <input.bam> [<output.bai>]

--stephen

**Comment by mschilli87** [comment]
@stephenwilliams22: Could you provide a link to the page containing the wrong SYNOPSIS?

**Comment by sambrightman** [comment]
https://www.google.com/search?q=sambamba+index&btnI=I

**Comment by mschilli87** [comment]
direct link: http://lomereiter.github.io/sambamba/docs/sambamba-index.html

**Comment by stephenwilliams22** [comment]
That’s the one. Thanks for correcting.
