### ISSUE TITLE
Clean up error message for sambamba-sort: couldn't parse (Allow memory command line option to be case independent.)

### ISSUE THREAD

**Issue by AMChalkie** [biod/sambamba#339]
Great software, minor comment: 

Allow memory command line option to be case independent.
More useful error message "couldn't parse command line option: 28g"

sambamba sort -t 32 -m 28g -o Aligned.out.srt.bam Aligned.out.bam
sambamba-sort: couldn't parse 
sambamba sort -t 32 -m 28G -o Aligned.out.srt.bam Aligned.out.bam
this works fine.

**Comment by pjotrp** [comment]
Noted.
