### ISSUE TITLE
line 11: 27182 Floating point exception(core dumped) 

### ISSUE THREAD

**Issue by jflucier** [biod/sambamba#342]
Hi

just to warn you that latest conda version of sambamba (0.6.6) produde the error mentionned in title when i call using this command:
 
`
sambamba flagstat -t 1 test.bam > test.flagstat.qc
`

I have tested all version > 0.6.3 and they all produce this error. Downgrading to version 0.6.3 worked perfectly

tks

JF

**Comment by pjotrp** [comment]
Can't reproduce the problem. Can you send me that test.bam?
