### ISSUE TITLE
how to reduce the bam file to different multiplier(5X,10X,15X......)

### ISSUE THREAD

**Issue by whiteorchid** [biod/sambamba#343]
The synthetic tumor BAM file was then downsampled into a range of sequencing depths. With the help of sambamba through the Swiss Army Knife application, these files were reduced to 5X, 10X, 15X, 20X, 30X, 40X, 50X, 60X, 90X, and 120X coverage files. [https://blog.dnanexus.com/tag/somatic-variant-calling/](url)

Hi,
I have seen that the bam file can be reduced to variable multiplier(5,10,15....) using your tool, I have a file 
 of ~100X ,want to do the similar reduce. It seems the **sambamba-slice** do this , still I don't know how to realize the reduce, can you give me some instructions ,best wishes!

**Comment by isthisthat** [comment]
I don't think `sambamba slice` is the right tool for this. We use `sambamba view -s <fraction>`. For instance if your current coverage is 100x and you want to sub-sample to 15x, you would specify `-s 0.15`, and so on. You would then need to re-mark duplicates in the downsampled bam: `sambamba markdup downsampled.bam dupmarked.bam`. This would give you an unbiased 15% sample of your original bam.

**Comment by pjotrp** [comment]
Rigorous downsampling is a recurring wish - certainly at speed. I wrote some code for it, but the implementation is not satisfactory yet. It turns out to be a tricky problem. 

As @isthisthat suggests you can fraction the output right now.
