### ISSUE TITLE
sambamba index 0.6.7 takes 4x longer than 0.6.6 on the same files

### ISSUE THREAD

**Issue by carsonhh** [biod/sambamba#345]
Simple command --> sambamba index -t 20 any_large_file.bam

0.6.7 rarely uses more than 5 threads under top while 0.6.6 uses all 20 I gave it.

Test on 105GB bam file using 20 threads.
0.6.6 --> 3m35.989s
0.6.7 --> 12m44.751s

I see the same pattern on all files on multiple machines (both AMD and Intel).

**Comment by pjotrp** [comment]
Can you try http://files.genenetwork.org/software/contrib/sambamba-0.6.8-pre1 instead and report the result?

3d6a286947daebb44ac87b4ff2f16c66  sambamba-0.6.8-pre1

**Comment by carsonhh** [comment]
sambamba-0.6.8-pre1 is performing better.

0.6.8-pre1 --> 3m13.100s
0.6.6 --> 3m45.064s

**Comment by pjotrp** [comment]
Thanks for trying. Yes, it is a compilation thing. The new Dlang+LLVM is faster.
