### ISSUE TITLE
sambamba (release 0.6.7) had abnormally finished with error code 35584

### ISSUE THREAD

**Issue by gskrasnov** [biod/sambamba#346]
Dear Authors,

sambamba (release 0.6.7) had abnormally finished with error code 35584
I tried to sort my BAM file (available [here](http://194.226.21.15/temp/MME03.sn.bam)) and got `segmentation fault` error.

However, sambamba has produced normally sorted final BAM file (available [here](http://194.226.21.15/temp/MME03.bam)) + index *.bai

command line:
```/sambamba_v0.6.7 sort --memory-limit 12000000000 --nthreads 6 --tmpdir ./MME03.temp --out MME03.bam MME03.sn.bam```

**There are 1870 reference scaffolds/contigs** and a large proportion of reads from the mitochondrial genome

**Comment by pjotrp** [comment]
On running latest I get no errors:

```
~/sambamba-0.6.8-pre1 sort --memory-limit 12000000000 --tmpdir ./MME03.temp --out MME03.bam MME03.sn.bam    

penguin2:~/data/sambamba/issue346$ ls -lrt 
-rw-r--r-- 1 pjotr pjotr 1439421481 Apr  1 07:47 MME03.sn.bam
-rw-r--r-- 1 pjotr pjotr       7896 Apr  2 09:12 MME03.sn.bam.bai
-rw-r--r-- 1 pjotr pjotr  890369670 Apr  2 09:16 MME03.bam
-rw-r--r-- 1 pjotr pjotr     475792 Apr  2 09:16 MME03.bam.bai
```

Are you running on a Xeon E5 per chance? See #335

**Comment by pjotrp** [comment]
DL http://files.genenetwork.org/software/contrib/sambamba-0.6.8-pre1

**Comment by gskrasnov** [comment]
Thank you, Pjotrp!

No, I'm running sambamba on Xeon E7- 8837 @8 threads

I tried the updated 0.6.8-pre1 and everything went fine.
