### ISSUE TITLE
Is sambamba-markdup library aware?

### ISSUE THREAD

**Issue by yuankunzhu** [biod/sambamba#349]
Wondering if `markdup` handles BAM with multiple lanes/libraries in a similar way as `Picard MarkDuplicats`, where only reads from the same `@RG LB` will be taken into account for duplicates marking? 
https://gatkforums.broadinstitute.org/gatk/discussion/6199/picard-mark-duplicates-handling-of-library-information

**Comment by dpryan79** [comment]
Isn't the library ID taken into account in the comparison? For example the library IDs would be part of the comparison here: https://github.com/biod/sambamba/blob/master/sambamba/markdup.d#L764

**Comment by pjotrp** [comment]
The library ID is used by markdup.
