### ISSUE TITLE
view error while filtering 10X BAM file on [CB] tag

### ISSUE THREAD

**Issue by RichardCorbett** [biod/sambamba#353]
Hey there.

This probably isn't a bug, but rather confused user error.

I'm trying to filter a 10X generated BAM file based on the value of a tag.  I can use this version of sambamba to do all the usual operations on this BAM file so there appears to only be a problem when I try this one task.

My command:
/home/rcorbett/bin/sambamba_v0.6.6 view -f bam -F "[CB]==TTTGCATGTAACGC-1" myBam.bam > newBam.bam

The error:
sambamba-view: invalid symbol in input stream at position 11

I've tried using spaces and/or different quotes, and escaping the dash but I keep getting the same error, though the position report can change depending on what I try.

thanks
RIchard

**Comment by pjotrp** [comment]
Thanks, I'll take a look later.
