### ISSUE TITLE
Upgrade htslib

### ISSUE THREAD

**Issue by pjotrp** [biod/sambamba#355]
It would be good to update to the latest, not least for #280 and current bioconda packaging attempts

**Comment by pjotrp** [comment]
@brainstorm adding you to the participants.

**Comment by pjotrp** [comment]
Actually, current thinking is to drop CRAM support. Anyone using that with sambamba?

**Comment by brainstorm** [comment]
I would probably have used it soon, pity :/

**Comment by Poshi** [comment]
Here we are using sambamba for many tasks, and a couple weeks ago we started thinking on moving to cram to try to reduce disk usage. In fact, for us, it would be good not only to keep the CRAM support, but also to enhance it (with little quirks like the ones samtools offer: using a reference/embedding it/not using any reference, choosing which compression algorithm to use, giving the opportunity of saving space by losing the IDs, choosing which tags must be kept and which must be dropped, keeping qualities or binning them...).

**Comment by pjotrp** [comment]
The plan is to work on the variant graph (VG) and column based BAM. 

CRAM support can still be an option in time. Personally I am not fond of the CRAM format in pipelines. For lossless storage it can be an idea, but there are newer formats that outperform CRAM. Personally I would like take the road with VG for cheap storage.
