### ISSUE TITLE
sort removing tags from @RG header

### ISSUE THREAD

**Issue by Kurt-Hetrick** [biod/sambamba#356]
Hello, when using sambamba sort on a bam file, i am finding that the PM tag for the RG header is being stripped out. I am using sambamba 0.6.7

bam file (brief particulars are that file is created with bwa mem 0.7.15 | samblaster | picard AddOrReplaceReadGroups | picard markduplicates {from querysort, v 2.17.0}) before sambamba sort

samtools view -H foo.dup.bam | grep ^@RG
@RG     ID:foo  LB:foo  PL:ILLUMINA     SM:foo  PU:foo  CN:foo DT:2017-12-10T00:00:00-0500     PG:foo  PM:HiSeq2500_HighOutput

then after running sambamba sort, the PM tag has been removed.

/mnt/research/tools/LINUX/SAMBAMBA/sambamba_v0.6.7/sambamba sort -o bar.bam foo.dup.bam

khetric1@c6100-9> samtools view -H bar.bam | grep ^@RG
@RG     ID:foo  CN:CIDR DT:2017-12-10T00:00:00-0500     LB:foo  PG:foo  PL:ILLUMINA     PU:foo  SM:foo

I couldn't find this in open or closed issues.

Thanks in advance,

Kurt

**Comment by pjotrp** [comment]
Thanks for the report. I'll check it.
