### ISSUE TITLE
How to merge temporal files from sort command?

### ISSUE THREAD

**Issue by TainVelasco-Luquez** [biod/sambamba#367]
* Versions
sambamba 0.6.7
samtools 1.9-33-g2d34e15
Using htslib 1.9

* Command
/usr/bin/time -v -o log.time sambamba sort -t 23 -m 2G -l 2 -p star_outputAligned.toTranscriptome.out.bam -o star_outputAligned.toTranscriptome.out.sorted.bam

So this is the story: Running sambamba and samtools sort was generating truncated bam files from the STAR output mapped to transcriptome (file size ~30Gb). So reading several posts I played with the `-m`and `-l`options, though the files generated, when generated, also were truncated and no EOF block detected so further analysis were halted.

The issue is: Sambamba is not generating any outpt files, though temporal files in /tmp/sambamba-xxx/ are present, valid and with the EOF.

The questions are:
1. How can I solve this issue?
2. Is there a way to use the already created temporal files to get the final `sorted.bam`? I have alreadt tried `sambamba merge -p -t 23 -l 3 -H final.sorted.bam *.bam.*`in the sambamba's temporal dir, though no output is generated.

**Additional info**
* Tail of the STAR output aligned to transcriptome with the EOF block:

```
tail star_outputAligned.toTranscriptome.out.bam | hexdump -C
00000b30  7a 8a f2 5d 24 03 91 24  39 ba 1a 48 c2 fd 91 e7  |z..]$..$9..H....|
00000b40  e4 b7 9d 0d 1f 01 d0 de  e4 31 9a 96 38 2d 02 cd  |.........1..8-..|
00000b50  f9 7f 36 bc 53 12 81 f9  00 00 1f 8b 08 04 00 00  |..6.S...........|
00000b60  00 00 00 ff 06 00 42 43  02 00 1b 00 03 00 00 00  |......BC........|
00000b70  00 00 00 00 00 00                                 |......|
00000b76
```
* Tail of the output from sambamba sort, when it was generated ouput, from star_outputAligned.toTranscriptome.out.bam without the EOF block:

```
tail star_outputAligned.toTranscriptome.out.bam | hexdump -C
00000820  5a 87 00 96 e0 d9 88 f4  be f8 0c 46 e9 ac df 00  |Z..........F....|
00000830  9e d2 57 04 4f 4e 23 84  7b 09 4d a5 1e dd 58 0a  |..W.ON#.{.M...X.|
00000840  bb 4e a4 85 42 cc 6f 68  44 fa bf 36 d3 b8 c7 c5  |.N..B.ohD..6....|
00000850  fe 00 00                                          |...|
00000853
```

*  Tail of one of the 10 temporal files created by sambamba in its `/tmp/sambamba/` dir with the EOF block. Furthermore, when using samtools quickcheck there is no complaint.

```
tail star_outputAligned.toTranscriptome.out.bam.9 | hexdump -C
000004b0  07 c5 7c e2 ff 03 e2 ec  3a f0 77 d1 00 00 1f 8b  |..|.....:.w.....|
000004c0  08 04 00 00 00 00 00 ff  06 00 42 43 02 00 1b 00  |..........BC....|
000004d0  03 00 00 00 00 00 00 00  00 00                    |..........|
000004da
```
* The machine has enough RAM and disk space for the files

 Best,

Tain

**Comment by pjotrp** [comment]
@TainVelasco-Luquez can you capture the output of stdout and stderr? Looks to me there is an error on the input file.

**Comment by TainVelasco-Luquez** [comment]
Dear @pjotrp 

I finally spot the error. I was connecting the server through ssh, and I haven't realised that every time I closed the ssh connection all my processess were also halted, among those, sambamba's sort. So this generated truncated files without the EOF block.

Now I am safe using tmux.

Sorry for the mistake,

Tain.
