### ISSUE TITLE
sambamba mpileup with reference

### ISSUE THREAD

**Issue by feihongloveworld** [biod/sambamba#368]
hi sir：
       i want to use ‘samtools  mpileup -f human_g1k_v37_decoy.fasta -l somatic.snv.vcf.bed final.bam ’；
       which parameter can sent reference fasta to ‘sambamba  mpileup’ ？？
       looking forward to your reply。thank you。

**Comment by pjotrp** [comment]
Thank you for using Sambamba.

For non-development questions please use our [mailing list](https://groups.google.com/forum/#!forum/-discussion). 

For the use of this issue tracker see also our [README](https://github.com/biod/sambamba#getting-help).
