### ISSUE TITLE
Makefile.docker requires ldmd2 to be installed locally

### ISSUE THREAD

**Issue by fwip** [biod/sambamba#373]
Hi,

I tried to compile sambamba using Docker on my Mac, and found that it still requires ldmd2 to be installed locally on the system. I believe the offending line is here: https://github.com/biod/sambamba/blob/v0.6.8/Makefile.docker#L42 - the `$(shell which ldmd2)` fails if there is no local version of `ldmd2` available.

I am not sure what the appropriate fix here is, but it seems like the right thing to do might be to take the version information from the docker container's version of `ldmd2` instead.

Sambamba version:  v0.6.8 (96d1b7).
Script: `make -f Makefile.docker`

**Comment by fwip** [comment]
Oh, sorry, those versions work fine. I wanted to have a go at compiling it myself, to see if I could hack on it a little bit (mostly for fun).

**Comment by pjotrp** [comment]
That would be really cool! If you check the .travis.yml file in the source tree you can see we build for macos on Travis which works out of the box: https://travis-ci.org/biod/sambamba/jobs/442531351
If you check that output you can see how you can install ldc on macos and compile everything. I suggest to try that. Use ldc 1.11 and not 1.12 - the latter is giving us problems.
