### ISSUE TITLE
Add fasta indexing and slicing functionalities  

### ISSUE THREAD

**Issue by emi80** [biod/sambamba#374]
These could include:

- indexing fasta files
- getting sequences by region queries
- storing fasta files in an indexed and compressed format (e.g. bgzip)

**Comment by emi80** [comment]
from @george-githinji 

https://seqan.readthedocs.io/en/seqan-v2.0.2/Tutorial/IndexedFastaIO.html

**Comment by pjotrp** [comment]
@emi80 I think we can close this, right?

**Comment by emi80** [comment]
HI @pjotrp, apologies for the late reply. 

Yes, we can close this issue.
