### ISSUE TITLE
sambamba depth --  open too many files

### ISSUE THREAD

**Issue by YPGG1234** [biod/sambamba#377]
hi,everyone,
i meet a problem when i use “sambamba depth” to handle a bam file.It reports “ **_sambamba-depth: Cannot open or create file 'XXX_clean_dedup.bam' : Too many open files_**”. There is only one bam file and i had already dedup with Picard，but when i use “sambamba depth”,it  works wrong.I had test “sambamba depth” with other bam files,there are all  run correctly.I don't know why.Can somebody help me?

**Comment by pjotrp** [comment]
Check open files with https://www.cyberciti.biz/faq/howto-linux-get-list-of-open-files/. Linux often allows for 1024 open files. You can increase that.
