### ISSUE TITLE
Add a new sorting method to set mates of the same alignment adjacent as required by RSEM

### ISSUE THREAD

**Issue by emi80** [biod/sambamba#379]

**Comment by pjotrp** [comment]
Thanks @emi80. Probably a good idea to add a test to the test suite.

**Comment by emi80** [comment]
Hi @pjotrp, yes definitely. I was planning to add one and I already have the test data. I just wanted to make the pull request first, for reference.

Thanks

**Comment by pjotrp** [comment]
https://github.com/biod/sambamba/pull/383
