### ISSUE TITLE
sambamba-sort error  sometimes

### ISSUE THREAD

**Issue by metoru** [biod/sambamba#381]
version of sambamba：0.68

* the command line or bash script used (feel free to shorten paths and filenames)
     sambamba view -h -S --format=bam 2-A1-D1.sam >tmp.bam
     sambamba sort -m 7000000000 tmp.bam

I  faied in runing the command sometimes in Sun Grid Engine .
   The erro  is "sambamba-sort: Unable to write to stream"
I hope you can give me some sugesstion ！
-->

**Comment by pjotrp** [comment]
See #218
