### ISSUE TITLE
issue on CRAM:  can't resolve www.ebi.ac.uk:80: System error

### ISSUE THREAD

**Issue by dolittle007** [biod/sambamba#388]
sambamba version 0.6.8

sambamba view -T $HOME/database/genome/hg38.fa -f cram test.bam -o test.cram

It pop ups a warning message:  can't resolve www.ebi.ac.uk:80: System error.
How to suppress it?

**Comment by milankovacevicsbg** [comment]
**sambamba version 0.7.0**

CMD:
sambamba-0.7.0 view --cram-input --nthreads=8 --format=bam merged-normal.filtered.cram -o merged-normal.filtered.bam

ERROR:
can't resolve www.ebi.ac.uk:80: System error
Failed to populate reference for id 20
Slice ends beyond reference end.
Unable to fetch reference #20 11038960..14992653
can't resolve www.ebi.ac.uk:80: System error
Failed to populate reference for id 20
Slice ends beyond reference end.
Unable to fetch reference #20 16339775..18977207
can't resolve www.ebi.ac.uk:80: System error
Failed to populate reference for id 20
Slice ends beyond reference end.
Unable to fetch reference #20 15599451..16339850
can't resolve www.ebi.ac.uk:80: System error
Failed to populate reference for id 20
Slice ends beyond reference end.

After which tool just fails. Any idea why? Thanks!

**Comment by pjotrp** [comment]
Sambamba uses an older htslib for CRAM which has 

        htslib/cram/cram_io.c:  ref_path = "http://www.ebi.ac.uk:80/ena/cram/md5/%s";

I recommend against using sambamba for CRAM. We'll rip the support out most likely.

**Comment by milankovacevicsbg** [comment]
Thanks, Pjotr!
