### ISSUE TITLE
Sambamba + BioD + GSoC idea

### ISSUE THREAD

**Issue by heuermh** [biod/sambamba#390]
Re:

Taking the fastest sequence transforming software in the world to the next level
https://obf.github.io/GSoC/ideas/#taking-the-fastest-sequence-transforming-software-in-the-world-to-the-next-level

I'd be the ADAM author to help mentor.  Would this issue be a good place to discuss?

**Comment by pjotrp** [comment]
Do you mind sending me an E-mail? pjotr dot public34 at thebird.nl

**Comment by pjotrp** [comment]
I sent you an E-mail.

**Comment by heuermh** [comment]
Thank you, @pjotrp
