### ISSUE TITLE
Subsampling with sambmaba produces wrong number of reads

### ISSUE THREAD

**Issue by mrshope93** [biod/sambamba#392]
Hi,

I am trying to subsample bam files using sambamba and I get somewhat unexpected number of reads in the output file. I am using sambamba 0.6.7 and the following command for subsampling:

sambamba view -h -t 56 -f bam --subsampling-seed=123 -s $fraction $bam -o $name\_$varname\.bam

My starting file has 97541577 reads. I am trying to subsample a fraction of 0.8137260791. This should result in ~ 79372125 reads. However, the output of sambamba contains 89908779 reads. I don't think there should be anything wrong with the original bam file. At least when I use samtools view -s, I get an expected number of reads, very close to 79372125. I would really appreciate any advice on this issue - is this a known bug or am I doing smth wrong?

Best wishes,

Nadya

**Comment by mrshope93** [comment]
I have tried running -t 1, thinking maybe something happens during parallelization, but got exactly the same number of reads 89908779, which is much larger than I expect.

**Comment by mrshope93** [comment]
I have been running the exactly same command in the past for smaller bam files, and haven't noticed any deviation from the expected number of reads (not more than 0.5%). I am wondering, if maybe the size of the inut file can be causing issues...

**Comment by isthisthat** [comment]
I've noticed that when sub-sampling the same bam twice, the second run will not throw out the expected number of reads. Are you sub-sampling multiple times?

**Comment by pjotrp** [comment]
Also discussed in #428
