### ISSUE TITLE
testSliceMultipleRegionsBed fails

### ISSUE THREAD

**Issue by pjotrp** [biod/sambamba#400]
testSliceMultipleRegionsBed segfaults for Linux but passes for OSX. See https://travis-ci.org/biod/sambamba/jobs/538802569

**Comment by scalavision** [comment]
will this be fixed soon ?

I would like to try to make a nixpkgs for this amazing library if possible, but need all the tests passing.

**Comment by pjotrp** [comment]
Let me take a look later in the week.

**Comment by pjotrp** [comment]
Turns out this failure is another variant of #393

**Comment by scalavision** [comment]
Thanks a lot! :-)

**Comment by pjotrp** [comment]
Should be fixed.
