### ISSUE TITLE
filtering uniquely mapped reads results in odd number of reads in PE data

### ISSUE THREAD

**Issue by rikrdo89** [biod/sambamba#410]
When using -F "[XS]==null" to get uniquely mapped reads, I  get a odd number of reads, despite having paired-end data which should result in an even number of reads. is there a way to only get the pairs that are uniquely mapped? I tried adding "proper_pair" but it still resulted in an odd numbers of reads

**Comment by pjotrp** [comment]
It probably requires a new feature. Closing this until someone wants to write the code :)
