### ISSUE TITLE
Feature request: absolute value operator in filter statements

### ISSUE THREAD

**Issue by tzuni** [biod/sambamba#415]
I'm trying to separate reads by the observed template size (for ATACseq data). Since the template size is given a sign depending on the orientation of each read, it makes it hard to use a simple one step comparison to the desired length. It would be great to be able to use something like this as a filter:

```
sambamba view -F "abs(template_size) > 100" ex.bam
```

Just putting it out there in case it's an easy add for anyone.

Thanks for the great tool!

**Comment by pjotrp** [comment]
Hi @tzuni, feel free to send a patch.
