### ISSUE TITLE
bed file input for sambamba dept filter outputing unrequested position?

### ISSUE THREAD

**Issue by duartemolha** [biod/sambamba#417]
Hi 

I was using sambamba depth to get the allele counts on my position using an input bed file
and I was a bit confused about the output

my bed file contains this position:
4       106155058       106155059

as bed file format is a 0based positional format I am expecting that sambamba would output the basepair numbers on position 106155059 of chromosome 4

whoever the output I  get is giving me the counts on the start coordinated of the bed file... 

4       106155058       987     987     0       0       0       0       0       Singles-3-NA18527_S3_L001       y

which (assuming sambaba is a 1base positional format ) is not the intended target in the input bed file)

Can you explain?

Many thanks

Duarte

**Comment by duartemolha** [comment]
Update... Based on the results I am getting it seems sambamba reporting coordinate is 0 base  

I used as test a file contaings a range

4       106155050       106155060

REF     POS     COV     A       C       G       T       DEL     REFSKIP SAMPLE  FLAG
Processing reference #4 (4)
4       106155050       779     0       0       0       779     0       0       sample y
4       106155051       798     798     0       0       0       0       0       sample y
4       106155052       796     0       0       795     1       0       0       sample y
4       106155053       807     806     1       0       0       0       0       sample y
4       106155054       815     814     0       1       0       0       0       sample y
4       106155055       820     0       0       0       820     0       0       sample y
4       106155056       813     0       0       0       813     0       0       sample y
4       106155057       826     0       826     0       0       0       0       sample y
4       106155058       835     835     0       0       0       0       0       sample y
4       106155059       850     850     0       0       0       0       0       sample y

Based on this we can see the sequence on this region is :
TAGAATTCAA

This corresponds to bp position 106155051 .. to ..106155060 (hg19)
Translating this to a valid coordinate bed file it would be correctly
4       106155050       106155060

But on the output of sambamba the position indicated by sambamba is off by one (or is 0based)

because for Sambamba the reporting is 
4       106155050       106155059

**Comment by pjotrp** [comment]
Please check the other issues first like #221.
