### ISSUE TITLE
Please port tools and test suite to Python3

### ISSUE THREAD

**Issue by tillea** [biod/sambamba#422]
Hi,
as you probably know Python2 is EOL at 1.1.2020.  Debian 11 will not contain Python2 any more and thus we need to port every package to Python3 (or kick it).  I have used 2to3 to create a [patch](https://salsa.debian.org/med-team/sambamba/blob/master/debian/patches/2to3.patch) for your kind inspection.  I admit I can not check that patch since the build error we discussed in private mail but the Python3 conversion does not look really complicated so I'd expect it to be fine.
Kind regards, Andreas.

**Comment by pjotrp** [comment]
Thanks @tillea. I'll take a look soon.

**Comment by pjotrp** [comment]
Thanks @tillea. These were fixed.
