### ISSUE TITLE
Incompatible with OSX Catalina

### ISSUE THREAD

**Issue by danielecook** [biod/sambamba#424]
Sambamba can no longer be used on the latest version of Mac OSX

Tested with version 0.6.8; I also experimented with building but I do not see a straightforward way to build for version 0.7.1.

```
dyld: lazy symbol binding failed: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /usr/local/bin/sambamba
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /usr/local/bin/sambamba
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6
```

**Comment by pjotrp** [comment]
Appears to be a small problem. I don't run non-free software, but if someone fixes it we are happy to accept the patches.

**Comment by dpryan79** [comment]
Has there been any resolution to this? It appears to be an issue with DMD on OSX and perhaps just using a newer version of DMD to compile things will solve the issue.

Xref: https://github.com/dlang/druntime/pull/2666

**Comment by pjotrp** [comment]
I'll do some work on sambamba soon. Hopeful travis-ci will help sort the OSX stuff.

**Comment by marcelm** [comment]
I can confirm that compiling Sambamba with LDC 1.17 will fix the problem, see bioconda/bioconda-recipes#20276.

**Comment by pjotrp** [comment]
That is great news :+1:
