### ISSUE TITLE
markdup: Barcode-aware duplicate marking

### ISSUE THREAD

**Issue by pontushojer** [biod/sambamba#427]
I am really enjoying the speed of sambamba-markdup. However, there is a very handy option in [picard-tools MarkDuplicates](https://broadinstitute.github.io/picard/command-line-overview.html#MarkDuplicates) to perform barcode-aware duplicate marking that I am missing. Is there any possibly for this feature to be added in the future?

**Comment by pjotrp** [comment]
It should not be too hard, but it needs someone who has the itch to scratch :).

**Comment by pjotrp** [comment]
I am closing the issue. If someone wants to work on it it can be reopened.
