### ISSUE TITLE
sambamba validate does not produce output

### ISSUE THREAD

**Issue by elcortegano** [biod/sambamba#430]
I am running `sambamba validate file.bam` with some BAM files, but this does not produce any output. Only:

    sambamba 0.7.1
     by Artem Tarasov and Pjotr Prins (C) 2012-2019
        LDC 1.17.0 / DMD v2.087.1 / LLVM8.0.1 / bootstrap LDC - the LLVM D compiler (1.17.0)

This is happening for files both with errors and without them (validated with picard).

Am I running this in a wrong way? Other tools as markdup seem to run fine.

**Comment by pjotrp** [comment]
If you read the source code you should be able to figure out what validate does.
