### ISSUE TITLE
sambamba-view error with pacbio SAM files

### ISSUE THREAD

**Issue by elcortegano** [biod/sambamba#431]
I am trying to produce BAM files from pacbio SAM files aligned with NGMLR. When I run:

    sambamba view -f bam -o file.bam file.sam

I got the following error:

    sambamba-view: Error reading BGZF block starting from offset 0: wrong BGZF magic

What is wrong with this? samtools view works fine over the same file.

**Comment by pjotrp** [comment]
The BAM file is not bgzf encoded.
