### ISSUE TITLE
sambamba merge with stdout not working

### ISSUE THREAD

**Issue by nh13** [biod/sambamba#435]
`sambamba merge /dev/stdout 1.bam 2.bam > out.bam` does not work on 0.6.6 and 0.7.1 installed via bioconda on OSX.  It looks like I omit the `> out.bam` pipe, I get the BAM file printed to stdout (crazy characters to the terminal).  Any ideas?

**Comment by pjotrp** [comment]
The crazy characters are the BAM output. Try outputting SAM instead.
