### ISSUE TITLE
sambamba depth output coordinate system

### ISSUE THREAD

**Issue by tahuh** [biod/sambamba#445]
Hi

I am using sambamba version `0.7.0` and `0.7.1`

I have tested the depth format to count up the bases with command below

`sambamba depth base -L chr7:55191822-55191823 in.bam`

`0.7.0` produce as shown below

```
sambamba 0.7.0
 by Artem Tarasov and Pjotr Prins (C) 2012-2019
    LDC 1.10.0 / DMD v2.080.1 / LLVM6.0.1 / bootstrap LDC - the LLVM D compiler (0.17.4)

REF	POS	COV	A	C	G	T	DEL	REFSKIP	SAMPLE
Processing reference #7 (chr7)
chr7	55191821	1819236	470	540	7888	1810336	1	0	sample
chr7	55191822	1820067	928	68	1818295	694	82	0	sample
```

`0.7.1` shows

```
sambamba 0.7.1
 by Artem Tarasov and Pjotr Prins (C) 2012-2019
    LDC 1.17.0 / DMD v2.087.1 / LLVM8.0.1 / bootstrap LDC - the LLVM D compiler (1.17.0)

REF	POS	COV	A	C	G	T	DEL	REFSKIP	SAMPLE
Processing reference #7 (chr7)
chr7	55191821	1819236	470	540	7888	1810336	1	0	sample
chr7	55191822	1820067	928	68	1818295	694	82	0	sample
```

Is sambamba designed to flush output in zero based context or is this problem is a bug?

Thanks

**Comment by pjotrp** [comment]
If you search for https://github.com/biod/sambamba/issues?q=is%3Aissue+zero you'll find more.

**Comment by tahuh** [comment]
Hi @pjotrp 
I found the answer via link you have attatched (link : https://github.com/biod/sambamba/issues/293)

Now I think it is okay to close this issue.
Thanks!
