### ISSUE TITLE
Sambamba not running in OSX Catalina

### ISSUE THREAD

**Issue by juulluu21** [biod/sambamba#449]
Hi: I am trying to run Smabamba in OSX Catalina. I get this in terminal:

dyld: lazy symbol binding failed: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /usr/local/Cellar/sambamba/0.6.8/bin/sambamba
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _dyld_enumerate_tlv_storage
  Referenced from: /usr/local/Cellar/sambamba/0.6.8/bin/sambamba
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6

I have tried different versions of sambamba. Same issue. I think its a problem with my OSX Catalina.
How to fix this?

Thanks!

**Comment by pjotrp** [comment]
We don't support OSX though some people manage to run sambamba on it. A docker container may do the trick.

**Comment by pjotrp** [comment]
See #424
