### ISSUE TITLE
Feature request: Build sambamba with libdeflate

### ISSUE THREAD

**Issue by rhpvorderman** [biod/sambamba#450]
[Libdeflate](https://github.com/ebiggers/libdeflate) is a library that has zlib and gzip compatible bindings. Htslib can be build with libdeflate instead of zlib. 

Most of the time spent writing BAM files is actually compressing them. Libdeflate is much faster than zlib, so I wonder if this can be an improvement for sambamba.

**Comment by pjotrp** [comment]
That is an interesting idea and probably easy to implement for someone with some C background. Ruben, are you interested in trying yourself, or should we look for someone?

**Comment by rhpvorderman** [comment]
I have no C background whatsoever. I also don't have experience with C++ or D, so integrating libdeflate into sambamba would be quite challenging for me.

**Comment by pjotrp** [comment]
Just for perspective, the binding to zlib is in [zlib.d](https://github.com/biod/sambamba/blob/e4ae4fe6b2e886c4286ebe8d872c71f5036d522a/BioD/bio/core/utils/zlib.d#L1). Bgzf [compression](https://github.com/biod/sambamba/blob/e4ae4fe6b2e886c4286ebe8d872c71f5036d522a/BioD/bio/core/bgzf/compress.d#L24) is where it is used (see also decompress.d). It should not be too hard, but I don't have time for it. For Sambamba libdeflate may help a little, though Sambamba does compress/decompress bgzf blocks in parallel - that is where its speed comes from.

I'll close the issue. If someone wants to work on it it can be reopened.
