### ISSUE TITLE
Differences in output between depth region -m (v0.6.5 and v0.7.1)

### ISSUE THREAD

**Issue by RachelDuffin** [biod/sambamba#455]
Hi, 

I am trying to validate use of sambamba v0.7.1 depth region and have found there to be differences in the bed file outputs for mean coverage and read count between versions v0.7.1 and v0.6.5. I have tried running sambamba depth region without the -m flag and found that any differences disappeared.

I noticed there was a previous issue #290 that seems similar which described calculation of number of bases per region in mate overlap scenarios as buggy, and where the user also found that running without -m resulted in any differences disappearing.

This issue (#290) is still open - is this a bug and has it been fixed?

**Comment by pjotrp** [comment]
Sorry for the late reply. Sambamba is in maintenance mode, the bug may still be there.
