### ISSUE TITLE
additional header columns are removed

### ISSUE THREAD

**Issue by tolot27** [biod/sambamba#462]
Sambamba removes additional header columns like `DS:T` added by [Salmon](https://github.com/COMBINE-lab/salmon/releases/tag/v1.3.0) of input files in sam format.

How to reproduce:

Samtools:
```
echo -e "@SQ\tSN:NM_000014.6\tLN:4610\tDS:T" | samtools view -H -
@SQ     SN:NM_000014.6  LN:4610 DS:T
```

Sambamba:
```
echo -e "@SQ\tSN:NM_000014.6\tLN:4610\tDS:T" | sambamba view -q -S -H /dev/stdin
@HD     VN:1.3
@SQ     SN:NM_000014.6  LN:4610
```

Expected: All header information should be retained even if it is converted to BAM.

**Comment by pjotrp** [comment]
Hi @tolot27, thanks for pointing that out. Do you feel like submitting a patch yourself? It should not be too hard. First look in the code and see where the header gets parsed. Follow what happens with the contents and the writer.
