### ISSUE TITLE
could not make sambamba-ldmd2-64

### ISSUE THREAD

**Issue by An1e** [biod/sambamba#465]
i followed all the steps given on this website, however i failed when executing "make sambamba-ldmd2-64", and the error is "make: *** No rule to make target `sambamba-ldmd2-64'.  Stop." 

I've already installed ldc2 and added alias to my bash profile, but still can't figure out what's wrong with my mac.

really need your help, thanks a lot.

**Comment by pjotrp** [comment]
Sambamba builds on Mac. Examples are on travis:

https://travis-ci.com/github/biod/sambamba/jobs/482840606
