### ISSUE TITLE
Compiling from source v.0.8.0 fails

### ISSUE THREAD

**Issue by nadyawilliams** [biod/sambamba#473]
**Describe the bug**

Building  from source on CentOS 7.9
Downloaded prerequisite ldc (ldc2-0.17.6-linux-x86_64), set PATH an LIBRARY_PATH per ldc install path:
export PATH=$PATH:`pwd`/ldc2-0.17.6-linux-x86_64/bin
export LIBRARY_PATH=`pwd`/ldc2-0.17.6-linux-x86_64/lib

Running make failed with the following error:

mkdir -p bin/
compile single object...
ldc2 -singleobj -wi -I. -IBioD -g -J. -O3 -release -enable-inlining -boundscheck=off -L-lz -c -of=bin/sambamba-0.8.0.o utils/ldc_version_info_.d utils/lz4.d utils/strip_bcf_header.d BioD/contrib/undead/cstream.d BioD/contrib/undead/doformat.d BioD/contrib/undead/internal/file.d BioD/contrib/undead/stream.d BioD/contrib/undead/utf.d utils/version_.d BioD/bio/core/base.d BioD/bio/core/bgzf/block.d BioD/bio/core/bgzf/chunk.d BioD/bio/core/bgzf/compress.d BioD/bio/core/bgzf/constants.d BioD/bio/core/bgzf/inputstream.d BioD/bio/core/bgzf/outputstream.d BioD/bio/core/bgzf/virtualoffset.d BioD/bio/core/call.d BioD/bio/core/decompress.d BioD/bio/core/genotype.d BioD/bio/core/kmer.d BioD/bio/core/region.d BioD/bio/core/sequence.d BioD/bio/core/tinymap.d BioD/bio/core/utils/algo.d BioD/bio/core/utils/bylinefast.d BioD/bio/core/utils/exception.d BioD/bio/core/utils/format.d BioD/bio/core/utils/memoize.d BioD/bio/core/utils/outbuffer.d BioD/bio/core/utils/range.d BioD/bio/core/utils/roundbuf.d BioD/bio/core/utils/stream.d BioD/bio/core/utils/switchendianness.d BioD/bio/core/utils/tmpfile.d BioD/bio/core/utils/zlib.d BioD/bio/std/experimental/hts/bam/header.d BioD/bio/std/experimental/hts/bam/reader.d BioD/bio/std/experimental/hts/bam/writer.d BioD/bio/std/experimental/hts/bgzf.d BioD/bio/std/experimental/hts/bgzf_writer.d BioD/bio/std/experimental/hts/constants.d BioD/bio/std/experimental/hts/hashing.d BioD/bio/std/experimental/hts/logger.d BioD/bio/std/experimental/hts/pileup.d BioD/bio/std/experimental/hts/reads.d BioD/bio/std/experimental/hts/unpack.d BioD/bio/std/file/fai.d BioD/bio/std/file/fasta.d BioD/bio/std/file/fastq.d BioD/bio/std/genotype/maf.d BioD/bio/std/genotype/snp.d BioD/bio/std/hts/bam/abstractreader.d BioD/bio/std/hts/bam/bai/bin.d BioD/bio/std/hts/bam/bai/indexing.d BioD/bio/std/hts/bam/baifile.d BioD/bio/std/hts/bam/baseinfo.d BioD/bio/std/hts/bam/cigar.d BioD/bio/std/hts/bam/constants.d BioD/bio/std/hts/bam/md/core.d BioD/bio/std/hts/bam/md/operation.d BioD/bio/std/hts/bam/md/parse.d BioD/bio/std/hts/bam/md/reconstruct.d BioD/bio/std/hts/bam/multireader.d BioD/bio/std/hts/bam/pileup.d BioD/bio/std/hts/bam/randomaccessmanager.d BioD/bio/std/hts/bam/read.d BioD/bio/std/hts/bam/reader.d BioD/bio/std/hts/bam/readrange.d BioD/bio/std/hts/bam/reference.d BioD/bio/std/hts/bam/referenceinfo.d BioD/bio/std/hts/bam/region.d BioD/bio/std/hts/bam/splitter.d BioD/bio/std/hts/bam/tagvalue.d BioD/bio/std/hts/bam/validation/alignment.d BioD/bio/std/hts/bam/validation/samheader.d BioD/bio/std/hts/bam/writer.d BioD/bio/std/hts/iontorrent/flowcall.d BioD/bio/std/hts/iontorrent/flowindex.d BioD/bio/std/hts/sam/header.d BioD/bio/std/hts/sam/reader.d BioD/bio/std/hts/sam/utils/fastrecordparser.d BioD/bio/std/hts/sam/utils/recordparser.d BioD/bio/std/hts/snpcallers/maq.d BioD/bio/std/hts/snpcallers/simple.d BioD/bio/std/hts/thirdparty/msgpack.d BioD/bio/std/hts/utils/array.d BioD/bio/std/hts/utils/graph.d BioD/bio/std/hts/utils/samheadermerger.d BioD/bio/std/hts/utils/value.d BioD/bio/std/maf/block.d BioD/bio/std/maf/parser.d BioD/bio/std/maf/reader.d BioD/bio/std/range/splitter.d BioD/bio/std/sff/constants.d BioD/bio/std/sff/index.d BioD/bio/std/sff/read.d BioD/bio/std/sff/reader.d BioD/bio/std/sff/readrange.d BioD/bio/std/sff/utils/roundup.d BioD/bio/std/sff/writer.d sambamba/depth.d sambamba/fixbins.d sambamba/flagstat.d sambamba/index.d sambamba/main.d sambamba/markdup.d sambamba/markdup2.d sambamba/merge.d sambamba/pileup.d sambamba/slice.d sambamba/sort.d sambamba/subsample.d sambamba/utils/common/bed.d sambamba/utils/common/file.d sambamba/utils/common/filtering.d sambamba/utils/common/intervaltree.d sambamba/utils/common/ldc_gc_workaround.d sambamba/utils/common/overwrite.d sambamba/utils/common/pratt_parser.d sambamba/utils/common/progressbar.d sambamba/utils/common/queryparser.d sambamba/utils/common/readstorage.d sambamba/utils/common/tmpdir.d sambamba/utils/view/alignmentrangeprocessor.d sambamba/utils/view/headerserializer.d sambamba/validate.d sambamba/view.d thirdparty/mergesort.d thirdparty/unstablesort.d

**sambamba/markdup.d(41): Error: module stopwatch is in file 'std/datetime/stopwatch.d' which cannot be read**

There is no datetime in BioD/bio/std/  or in ./ldc2-0.17.6-linux-x86_64/import/std/
Is there some prerequisite that is missing or is there compatibility issue between sambamba and ldc versions?

**Comment by pjotrp** [comment]
Use a modern compiler.

**Comment by nadyawilliams** [comment]
A modern compiler would be intel or gcc. I do have both the latest
available, however your compilation is using ldc and
according to your document on the install page the version i used
 should be compatible.
Perhaps it would be useful to other users as well to make
 requirements more clear and specify
a matrix of versions compatibility.
