### ISSUE TITLE
Inaccessible google groups support forum

### ISSUE THREAD

**Issue by Poshi** [biod/sambamba#474]
I'm trying to access the support group which, according to the documentation, is supposed to be at https://groups.google.com/forum/#!forum/sambamba-discussion

For some reason, I'm getting an error of "Content not available". I tried with Chrome and Firefox, logged in a Google account and unlogged.

I'm not sure if this is a documentation bug and it should be changed to the current location or an issue with the Google group itself, but other groups I'm subscribed seems to work. Sorry to ask here, but it looks like the location of the support group has changed but the documentation has not been updated.

**Comment by pjotrp** [comment]
Please sign up and don't open new issues for things that are not clearly sambamba bugs. Please follow https://github.com/biod/sambamba#check-list

**Comment by Poshi** [comment]
I'm trying, but I cannot sign up to something that says, literally "Contingut no disponible" (in my language, which translates to "content not available"). I cannot access the group thru a search either. That's why I assumed the mailing list changed of location and it was a BUG in sambamba documentation.
In case the link is correct and for some reason (that I cannot see) I cannot access the group, then you are right, this is not a sambamba bug and I'm just left out without means of asking anything to anyone :-(

Well, just before posting this answer I tried again and now it worked. Now I can see the group and I can sign-in. Thanks.
