### ISSUE TITLE
do you support aggregation and dedup in one command?

### ISSUE THREAD

**Issue by AlisaGU** [biod/sambamba#481]
Hi,
sambamba is really quick, thanks for your efforts. But, I don't know if it supports aggregation and dedup in one command like this: [**Merge read groups and mark duplicates per sample (aggregation + dedup)**](https://gatk.broadinstitute.org/hc/en-us/articles/360035889471-How-should-I-pre-process-data-from-multiplexed-sequencing-and-multi-library-designs-).

Can I just pass the multiple inputs belonging to one sample to sambamba in a single command to merge and deduplicate them?

**Comment by pjotrp** [comment]
Nope.

**Comment by AlisaGU** [comment]
Thanks for your reply.
What should I do to achieve this? use sambamba-merge to merge and sambamba-markdup to dedup?

**Comment by AlisaGU** [comment]
Hi,
Do you agree with my idea?
