### ISSUE TITLE
Test suite error on Debian unstable

### ISSUE THREAD

**Issue by tillea** [biod/sambamba#497]
**Describe the bug**

I've observed a test suite error on Debian Salsa CI.  [here](https://salsa.debian.org/med-team/sambamba/-/jobs/3610054) you can find the full log to see what package versions were used.  The error is

    testIssue421
    shunit2:ERROR testIssue421() returned non-zero return code.
    testFastaIndex
    Indexing FASTA file...
    Ran 23 tests.
    FAILED (failures=1)

Kind regards, Andreas.

**Comment by pjotrp** [comment]
Hmmm. I should disable the fasta stuff.

**Comment by tillea** [comment]
Am Mon, Dec 05, 2022 at 07:41:47AM -0800 schrieb Pjotr Prins:
> Hmmm. I should disable the fasta stuff.

Please let me know if you have a patch / new release.

**Comment by pjotrp** [comment]
Should be fixed with new v1.0 release.

**Comment by pjotrp** [comment]
Done!
