### ISSUE TITLE
Minor subversion number missing in 1.0 release

### ISSUE THREAD

**Issue by Stikus** [biod/sambamba#500]
Thanks for 1.0 release.

But in previous releases we always have 3-digits version and release package have same version as program itself:
```
https://github.com/biod/sambamba/archive/refs/tags/v0.8.2.tar.gz
https://github.com/biod/sambamba/blob/v0.8.2/VERSION
0.8.2
```

Now we have a 2-digit branch and release, but 3-digit version of the resulting program:
```
https://github.com/biod/sambamba/archive/refs/tags/v1.0.tar.gz
https://github.com/biod/sambamba/blob/v1.0/VERSION
1.0.0
```

It broke our installation. Is it intended, or can you fix it?

**Comment by pjotrp** [comment]
Fair point :)

**Comment by serge2016** [comment]
Same here! Hope to see fast fix! Please)

**Comment by pjotrp** [comment]
Is it not working? I fixed it a few days ago. Changed the title too.
