### ISSUE TITLE
provide an example of pipping sambamba in documentation

### ISSUE THREAD

**Issue by DrRLS** [biod/sambamba#504]
I enjoy using Sambamba to in my processing pipeline. I am trying to pipe different commands to create a one liner to process SAM as input and get a sorted BAM file with marked duplicates if possible. This would avoid all the intermediate files generated without pipping. 

Can some provide some pointer on how to use sambamba to pipe the following tools, starting with a sam file and ending up with a sorted.dedup.bam?
sambamba view > sambamba sort > sambamba markdup

**Comment by pjotrp** [comment]
There are some options in the docs.
