### ISSUE TITLE
sambamba 1.0.1 build failure

### ISSUE THREAD

**Issue by chenrui333** [biod/sambamba#507]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  ldc2 -wi -I. -I./BioD:./BioD/contrib/msgpack-d/src -g -J. -O3 -release -enable-inlining -boundscheck=off -L=-flto=full -of=bin/sambamba-1.0.1 bin/sambamba-1.0.1.o  -L-lz -L-llz4
  ld: unknown option: -flto=full
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  Error: /opt/homebrew/Library/Homebrew/shims/mac/super/gcc failed with status: 1
  make: *** [bin/sambamba-1.0.1] Error 1
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/5892800197/job/15983167246?pr=139677
relates to Homebrew/homebrew-core#139677

**Comment by pjotrp** [comment]
it says  ld: unknown option: -flto=full
can you disable the switch?

**Comment by pjotrp** [comment]
We use the gcc linker by default.

**Comment by chenrui333** [comment]
that suggestion works for me.

**Comment by chenrui333** [comment]
@pjotrp removing the flag works for CI as well, closing the issue now.
