### ISSUE TITLE
"sambamba-view: not enough data in stream"

### ISSUE THREAD

**Issue by scatreux** [biod/sambamba#79]
Hi,

I'm getting an error: "sambamba-view: not enough data in stream" by running this command line:
/usr/local/bin/sambamba view -F 'mapping_quality > 0' -L /exome-12-callable-regions.bed -f bam -l 1 /bamfile1.bam > test.bam

I have done the following tests:
1. removing the -L BED file from the command line gets rid of the error
2. swapping the bamfile1.bam for a different bamfile2.bam and keeping the -L BED file in the command line also gets rid of the error.

So, it seems it is when the -L BED file and bamfile1.bam are in the same command line that I get the error. Can you please provide tips on how I can further narrow down on the issue?
I'm also happy uploading the BED and bamfile1.bam to a suggested place if it is helpful for debug.
I tried a samtools view of the -L BED and bamfile1.bam on the same command line and
that also completed successfully.

Many thanks
Severine

**Comment by annaquaglieri16** [comment]
Hi there, 

I can the same error when running:

sambamba markdup ${bamRG} ${bamDupl} -t 5 --show-progress

What was the solution to the problem previously? 

Thanks, 

Anna

**Comment by pjotrp** [comment]
Please address the mailing list first. Add what version of sambamba you are using. See https://github.com/biod/sambamba#reporting-a-sambamba-bug-or-issue

**Comment by annaquaglieri16** [comment]
Thanks for your answer! It is actually my fault, our servers had some faults and my bamfiles were corrupted at the end. Sorry for this and thanks for your time!

Anna

**Comment by pjotrp** [comment]
We'll improve on that error message. Thanks for reporting back :)
